### PR TITLE
closes#1 & #3

### PR DESCRIPTION
**Pull request by Tahany-Alswoidy**
create the city model and the get all the cities method in the controllers

### CODE REVIEW

**Review by Ammar-64 — DISMISSED** [review]
LGTM

**Comment by Ammar-64** [comment]
there's a conflict needs to be solved here

**Review by martinnajjar12 — DISMISSED** [review]
However City model was assigned to Tahany, I don't mind merging this PR to move forward.

**Review by martinnajjar12 — APPROVED** [review]
Good job Tahany. Well done

**Pull request merged**
